"""Physics utility modules for the flapping bot (e.g., aerodynamics)."""

from .qsm import FlappingQSMCfg, QuasiSteadyWingModel, WingQSMCfg
from .qsm_wang2016 import (
    WingGeometry,
    compute_aero_wrench,
    compute_aero_wrench_from_omega_alpha,
    cp_location_rotation,
    eta_shape_piecewise,
    rotation_matrix_i_from_c,
    transform_wrench_c_to_world,
)
from .qsm_delaurier1993 import (
    DeLaurierParams,
    DeLaurierStripLoads,
    DeLaurierStripWrench,
    compute_aero_wrench_delaurier1993,
    compute_delaurier_strip_loads,
    integrate_delaurier_strip_wrench,
    transform_wang_wrench_to_link,
    translate_wrench_moment,
)
from .delaurier_twist import (
    DELAURIER_DYNAMIC_TWIST_MODES,
    DeLaurierTwistKinematics,
    LegacyQdScaledTwistKinematics,
    compute_legacy_qd_scaled_twist,
    compute_delaurier_dynamic_twist,
    resolve_delaurier_phase,
    validate_delaurier_dynamic_twist_mode,
)
from .delaurier_airflow import (
    body_air_velocity_to_delaurier_section_velocity,
    compute_delaurier_axis_incidence,
)
from .tail_aero import TailAeroCfg, TailAeroModel, TailSurfaceCfg, TailSurfaceResult
from .tail_geometry import PlaceholderValue, TailGeometry, TailSurfaceGeometry, load_tail_geometry_from_urdf
from .wing_equivalent_ac import compute_area_weighted_quarter_chord_link_points
from .wing_geom_csv import WingGeomCsvInfo, build_wing_geometry_from_csv, infer_span_from_x_mid, load_wing_geom_csv
from .virtual_twist import VirtualTwistCfg, VirtualTwistState, solve_quasi_static_eta_tip, step_virtual_twist
from .measured_mass_properties import (
    BODY_INERTIA_TRIANGLE_TOLERANCE_KG_M2,
    BODY_LINK_MASS_PROPERTIES,
    BODY_MEASURED_U_FRD,
    FRD_TO_FLU,
    LEFT_WING_FROM_RIGHT_WING_LINK_MIRROR,
    LEFT_WING_LINK_MASS_PROPERTIES,
    MEASURED_FLAPPING_BOT_LINK_MASS_PROPERTIES,
    MEASURED_MASS_PROPERTIES_WORKBOOK_NAME,
    MEASURED_MASS_PROPERTIES_WORKBOOK_SHA256,
    RIGHT_WING_LINK_MASS_PROPERTIES,
    RIGHT_WING_MEASURED_W_R0_FRD,
    RigidBodyMassProperties,
    diagonal_inertia_kg_m2,
    inertia_triangle_margins_kg_m2,
    measured_three_link_total_mass_kg,
    transform_mass_properties,
    validate_mass_properties,
)
from .multibody_mass_distribution import (
    FLAPPING_BOT_PLANT_VARIANTS,
    MEASURED_MULTIBODY_DEFAULT_PLACEHOLDER_MASS_KG,
    MEASURED_MULTIBODY_PLACEHOLDER_LINK_NAMES,
    MEASURED_MULTIBODY_TOTAL_MASS_KG,
    MEASURED_WING_MULTIBODY_PLANT,
    NEAR_SINGLE_RIGID_BODY_PLANT,
    RuntimeMassProperties,
    build_measured_wing_multibody_tensors,
    measured_wing_multibody_runtime_properties,
    project_diagonal_inertia_to_triangle_cone,
    validate_flapping_bot_plant_variant,
)
from .multibody_wing_coupling import (
    ACTUAL_PER_WING_LINK,
    COMMANDED_BASE_EQUIVALENT,
    WING_AERO_COUPLING_MODES,
    PhysicalWingFlapKinematics,
    map_opposed_joint_states_to_physical_wing_kinematics,
    translate_wing_root_wrench_to_com_link,
    validate_wing_aero_coupling_mode,
)
from .sfwm_inertial_reference import (
    AminiSfwmInertialResponse,
    AminiSfwmLongitudinalParams,
    MEASURED_WING_NEUTRAL_DIHEDRAL_RAD,
    compute_amini_sfwm_inertial_response,
    measured_flapping_bot_amini_params,
)

__all__ = [
    "WingQSMCfg",
    "FlappingQSMCfg",
    "QuasiSteadyWingModel",
    "WingGeometry",
    "compute_aero_wrench",
    "compute_aero_wrench_from_omega_alpha",
    "cp_location_rotation",
    "eta_shape_piecewise",
    "rotation_matrix_i_from_c",
    "transform_wrench_c_to_world",
    "DeLaurierParams",
    "DeLaurierStripLoads",
    "DeLaurierStripWrench",
    "compute_aero_wrench_delaurier1993",
    "compute_delaurier_strip_loads",
    "integrate_delaurier_strip_wrench",
    "transform_wang_wrench_to_link",
    "translate_wrench_moment",
    "DELAURIER_DYNAMIC_TWIST_MODES",
    "DeLaurierTwistKinematics",
    "LegacyQdScaledTwistKinematics",
    "compute_delaurier_dynamic_twist",
    "compute_legacy_qd_scaled_twist",
    "resolve_delaurier_phase",
    "validate_delaurier_dynamic_twist_mode",
    "body_air_velocity_to_delaurier_section_velocity",
    "compute_delaurier_axis_incidence",
    "TailSurfaceCfg",
    "TailSurfaceResult",
    "TailAeroCfg",
    "TailAeroModel",
    "PlaceholderValue",
    "TailSurfaceGeometry",
    "TailGeometry",
    "load_tail_geometry_from_urdf",
    "compute_area_weighted_quarter_chord_link_points",
    "WingGeomCsvInfo",
    "load_wing_geom_csv",
    "infer_span_from_x_mid",
    "build_wing_geometry_from_csv",
    "VirtualTwistCfg",
    "VirtualTwistState",
    "solve_quasi_static_eta_tip",
    "step_virtual_twist",
    "RigidBodyMassProperties",
    "MEASURED_MASS_PROPERTIES_WORKBOOK_NAME",
    "MEASURED_MASS_PROPERTIES_WORKBOOK_SHA256",
    "BODY_INERTIA_TRIANGLE_TOLERANCE_KG_M2",
    "FRD_TO_FLU",
    "LEFT_WING_FROM_RIGHT_WING_LINK_MIRROR",
    "BODY_MEASURED_U_FRD",
    "RIGHT_WING_MEASURED_W_R0_FRD",
    "BODY_LINK_MASS_PROPERTIES",
    "LEFT_WING_LINK_MASS_PROPERTIES",
    "RIGHT_WING_LINK_MASS_PROPERTIES",
    "MEASURED_FLAPPING_BOT_LINK_MASS_PROPERTIES",
    "diagonal_inertia_kg_m2",
    "transform_mass_properties",
    "inertia_triangle_margins_kg_m2",
    "validate_mass_properties",
    "measured_three_link_total_mass_kg",
    "RuntimeMassProperties",
    "NEAR_SINGLE_RIGID_BODY_PLANT",
    "MEASURED_WING_MULTIBODY_PLANT",
    "FLAPPING_BOT_PLANT_VARIANTS",
    "MEASURED_MULTIBODY_TOTAL_MASS_KG",
    "MEASURED_MULTIBODY_PLACEHOLDER_LINK_NAMES",
    "MEASURED_MULTIBODY_DEFAULT_PLACEHOLDER_MASS_KG",
    "project_diagonal_inertia_to_triangle_cone",
    "measured_wing_multibody_runtime_properties",
    "build_measured_wing_multibody_tensors",
    "validate_flapping_bot_plant_variant",
    "ACTUAL_PER_WING_LINK",
    "COMMANDED_BASE_EQUIVALENT",
    "WING_AERO_COUPLING_MODES",
    "PhysicalWingFlapKinematics",
    "map_opposed_joint_states_to_physical_wing_kinematics",
    "translate_wing_root_wrench_to_com_link",
    "validate_wing_aero_coupling_mode",
    "AminiSfwmLongitudinalParams",
    "AminiSfwmInertialResponse",
    "MEASURED_WING_NEUTRAL_DIHEDRAL_RAD",
    "measured_flapping_bot_amini_params",
    "compute_amini_sfwm_inertial_response",
]
