"""Physics utility modules for the flapping bot (e.g., aerodynamics)."""

from .qsm import FlappingQSMCfg, QuasiSteadyWingModel, WingQSMCfg
from .qsm_wang2016 import (
    WingGeometry,
    compute_aero_wrench,
    compute_aero_wrench_from_omega_alpha,
    cp_location_rotation,
    eta_shape_piecewise,
    rotation_matrix_i_from_c,
    transform_wrench_c_to_world,
)
from .qsm_delaurier1993 import (
    DeLaurierParams,
    DeLaurierStripLoads,
    DeLaurierStripWrench,
    compute_aero_wrench_delaurier1993,
    compute_delaurier_strip_loads,
    integrate_delaurier_strip_wrench,
    transform_wang_wrench_to_link,
    translate_wrench_moment,
)
from .delaurier_twist import (
    DELAURIER_DYNAMIC_TWIST_MODES,
    DeLaurierTwistKinematics,
    LegacyQdScaledTwistKinematics,
    compute_legacy_qd_scaled_twist,
    compute_delaurier_dynamic_twist,
    resolve_delaurier_phase,
    validate_delaurier_dynamic_twist_mode,
)
from .delaurier_airflow import (
    body_air_velocity_to_delaurier_section_velocity,
    compute_delaurier_axis_incidence,
)
from .tail_aero import TailAeroCfg, TailAeroModel, TailSurfaceCfg, TailSurfaceResult
from .tail_geometry import PlaceholderValue, TailGeometry, TailSurfaceGeometry, load_tail_geometry_from_urdf
from .wing_equivalent_ac import compute_area_weighted_quarter_chord_link_points
from .wing_geom_csv import WingGeomCsvInfo, build_wing_geometry_from_csv, infer_span_from_x_mid, load_wing_geom_csv
from .virtual_twist import VirtualTwistCfg, VirtualTwistState, solve_quasi_static_eta_tip, step_virtual_twist
from .measured_mass_properties import (
    BODY_INERTIA_TRIANGLE_TOLERANCE_KG_M2,
    BODY_LINK_MASS_PROPERTIES,
    BODY_MEASURED_U_FRD,
    FRD_TO_FLU,
    LEFT_WING_FROM_RIGHT_WING_LINK_MIRROR,
    LEFT_WING_LINK_MASS_PROPERTIES,
    MEASURED_FLAPPING_BOT_LINK_MASS_PROPERTIES,
    MEASURED_MASS_PROPERTIES_WORKBOOK_NAME,
    MEASURED_MASS_PROPERTIES_WORKBOOK_SHA256,
    RIGHT_WING_LINK_MASS_PROPERTIES,
    RIGHT_WING_MEASURED_W_R0_FRD,
    RigidBodyMassProperties,
    diagonal_inertia_kg_m2,
    inertia_triangle_margins_kg_m2,
    measured_three_link_total_mass_kg,
    transform_mass_properties,
    validate_mass_properties,
)

__all__ = [
    "WingQSMCfg",
    "FlappingQSMCfg",
    "QuasiSteadyWingModel",
    "WingGeometry",
    "compute_aero_wrench",
    "compute_aero_wrench_from_omega_alpha",
    "cp_location_rotation",
    "eta_shape_piecewise",
    "rotation_matrix_i_from_c",
    "transform_wrench_c_to_world",
    "DeLaurierParams",
    "DeLaurierStripLoads",
    "DeLaurierStripWrench",
    "compute_aero_wrench_delaurier1993",
    "compute_delaurier_strip_loads",
    "integrate_delaurier_strip_wrench",
    "transform_wang_wrench_to_link",
    "translate_wrench_moment",
    "DELAURIER_DYNAMIC_TWIST_MODES",
    "DeLaurierTwistKinematics",
    "LegacyQdScaledTwistKinematics",
    "compute_delaurier_dynamic_twist",
    "compute_legacy_qd_scaled_twist",
    "resolve_delaurier_phase",
    "validate_delaurier_dynamic_twist_mode",
    "body_air_velocity_to_delaurier_section_velocity",
    "compute_delaurier_axis_incidence",
    "TailSurfaceCfg",
    "TailSurfaceResult",
    "TailAeroCfg",
    "TailAeroModel",
    "PlaceholderValue",
    "TailSurfaceGeometry",
    "TailGeometry",
    "load_tail_geometry_from_urdf",
    "compute_area_weighted_quarter_chord_link_points",
    "WingGeomCsvInfo",
    "load_wing_geom_csv",
    "infer_span_from_x_mid",
    "build_wing_geometry_from_csv",
    "VirtualTwistCfg",
    "VirtualTwistState",
    "solve_quasi_static_eta_tip",
    "step_virtual_twist",
    "RigidBodyMassProperties",
    "MEASURED_MASS_PROPERTIES_WORKBOOK_NAME",
    "MEASURED_MASS_PROPERTIES_WORKBOOK_SHA256",
    "BODY_INERTIA_TRIANGLE_TOLERANCE_KG_M2",
    "FRD_TO_FLU",
    "LEFT_WING_FROM_RIGHT_WING_LINK_MIRROR",
    "BODY_MEASURED_U_FRD",
    "RIGHT_WING_MEASURED_W_R0_FRD",
    "BODY_LINK_MASS_PROPERTIES",
    "LEFT_WING_LINK_MASS_PROPERTIES",
    "RIGHT_WING_LINK_MASS_PROPERTIES",
    "MEASURED_FLAPPING_BOT_LINK_MASS_PROPERTIES",
    "diagonal_inertia_kg_m2",
    "transform_mass_properties",
    "inertia_triangle_margins_kg_m2",
    "validate_mass_properties",
    "measured_three_link_total_mass_kg",
]
